from typing import Protocol

from app.domain.models import AuditEntry, HistoryEntry, Memory


class MemoryRepo(Protocol):
    """Vector store of memories, filtered by scope/visibility on read."""

    def upsert(self, memory: Memory, vector: list[float]) -> None: ...
    def patch(self, memory: Memory) -> None: ...  # update metadata, keep vector
    def get(self, memory_id: str) -> Memory | None: ...
    def delete(self, memory_id: str) -> None: ...
    def search(
        self, dense: list[float], text: str, scope_ids: list[str], top_k: int
    ) -> list[Memory]: ...
    def neighbors(
        self, dense: list[float], scope_ids: list[str], k: int = 5
    ) -> list[tuple[Memory, float]]: ...
    def list_by_scope(self, scope_ids: list[str]) -> list[Memory]: ...
    def by_semantic_key(self, key: str, scope_ids: list[str]) -> list[Memory]: ...
    def count(self) -> int: ...


class AuditRepo(Protocol):
    def append(self, entry: AuditEntry) -> None: ...
    def list(self, limit: int = 100) -> list[AuditEntry]: ...


class HistoryRepo(Protocol):
    def append(self, entry: HistoryEntry) -> None: ...
    def list(self, memory_id: str) -> list[HistoryEntry]: ...


class OrgRepo(Protocol):
    """Organization structure used to build a viewer's visible scope set."""

    def visible_scope_ids(self, profile_id: str) -> list[str]: ...
    def is_admin(self, profile_id: str) -> bool: ...
    def teams_of(self, profile_id: str) -> list[str]: ...
